# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
Summary:        explain built using CMake
Name:           explain
Version:        1.0.0
Release:        1%{?dist}
License:        unknown
Vendor:         Saturno

Source0:        %{name}-%{version}.tar.gz

BuildRequires:  cmake
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  nlohmann_json-devel
BuildRequires:  libcpr-devel

%define _unpackaged_files_terminate_build 0

%description
Fast command-line utility designed for terminal workflow automation and API querying.

%prep
%autosetup

%build
%cmake
%cmake_build

%install
%cmake_install

%files
%{_bindir}/explain

%changelog
* Sun Jul 04 2010 Eric Noulard <eric.noulard@gmail.com> - 1.0.0-1%{?dist}
- Generated by CPack RPM