# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/explain-1.0.0-1.x86_64
Summary:        explain built using CMake
Name:           explain
Version:        1.0.0
Release:        1%{?dist}
License:        unknown
Group:          unknown
Vendor:         Saturno















Prefix: /usr/local





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename explain-1.0.0-1.x86_64.rpm
%define _unpackaged_files_terminate_build 0





%description
Fast command-line utility designed for terminal workflow automation and API querying.

# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
%dir /usr/local
%dir /usr/local/bin
/usr/local/bin/explain




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.0.0-1%{?dist}
  Generated by CPack RPM (no Changelog file were provided)


