# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
Summary:        explain built using CMake
Name:           explain
Version:        1.0.0
Release:        1%{?dist}
License:        unknown
Group:          unknown
Vendor:         Saturno

%define _unpackaged_files_terminate_build 0

%description
Fast command-line utility designed for terminal workflow automation and API querying.

%prep

%build

%install
mkdir -p %{buildroot}%{_bindir}
if [ -f explain ]; then
    cp explain %{buildroot}%{_bindir}/
fi

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%{_bindir}/explain

%changelog
* Sun Jul 04 2010 Eric Noulard <eric.noulard@gmail.com> - 1.0.0-1%{?dist}
- Generated by CPack RPM